Cast variable to string
Using env approach:
CYPRESS_TESTRAIL_PROJECT_ID=55
Throws an error:
$ node_modules/.bin/cypress run 
...
Your configFile threw an error from: /var/www/cypress.config.js

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: projectId.replace is not a function
    at ConfigService.getProjectId (/var/www/node_modules/cypress-testrail/src/services/ConfigService.js:137:31)
    at new Reporter (/var/www/node_modules/cypress-testrail/src/Reporter.js:25:40)

Using console.log we get the numeric value which is the reason for the error. The following changes cast the value into string so .replace() is a valid function.